language: node_js

node_js:
  - "6"
  - "8"
  - "10"

branches:
  except:
    - /^dependabot\/.*$/

env:
  - ESLINT_VERSION=2
  - ESLINT_VERSION=3
  - ESLINT_VERSION=4

matrix:
  exclude:
  - node_js: "6"
    env: ESLINT_VERSION=3
  - node_js: "6"
    env: ESLINT_VERSION=4
  - node_js: "8"
    env: ESLINT_VERSION=3
  - node_js: "8"
    env: ESLINT_VERSION=4

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - yarn add eslint@$ESLINT_VERSION

deploy:
  provider: npm
  email: tobias.bieniek@gmx.de
  api_key:
    secure: RpFjofiuEqEovxfewpJv8FlPLN+EBSjllYuPz/qBjGv1+koVP+Y6E4ZExq/Zx5kP3EQ4oh3eYdxe0NV6da/f9Gqhz8w2HEdCRAbnbxKAw2LG9CWLr6yxjJDlToNrd0hrBcMdAVObjzZUMTVbhUMuTOWem4kFozYwZp/KAf8uYE2kfP1IUxKDeV3bFHAwXC/KrfgPE3m5Q8VUvwvoEDXf7ieRJM75akhTndtRvAQN3kKYvDuIzTmjazr0f/pRQkUablSExsqFKBu6d8xFrwp57ecSwOr292vf6Ye+fudaWcWK4FAseK3/G6XwokobeTFSL9BgDgB/z1k2NnwADeEKMq2iyGzNRky4tKckTHsmLrOx5ajet7Oa5bMbKfJqPp7Qy7oKnucnhGTq7/0tjr52XR/C04fpJBYiNnsppibF9AwhVakaNAVr1SB1tzSqjj6nqCVltuVElHuOGcC4lZQ6UlX+gJ7t8zTKK8SX/ajmXC2rgxAbrrNZfJ/GjE9lkjX8jV9uD8OmDQs8wc64Gok0GdD/wjG9x6Hms3DezNlEdXxtS/Gs96bJKOiXbZJ/8QjadIRlpFuTq0oYzaTyivE5cWl0sxbDNxdEOktDzxEWWgLSf6Z0pXevk6zExc4FmVohk1OrByEWpEZj3dyO113HsdfxsznziqXgeSNbEd0VUMc=
  on:
    tags: true
    repo: Turbo87/eslint-plugin-chai-expect
